blank_issues_enabled: false
contact_links:
  - name: Discord
    url: https://discord.gg/PxyTfhPBfu
    about: Please ask and answer questions here.
  - name: Wiki
    url: https://wiki.alumina.dev
    about: Please read the wiki before asking questions.
