name: Feature Request

description: Request a new feature for this project.

title: "[Feature Request] "

labels: [ "enhancement" ]

body:
  - type: textarea
    attributes:
      label: "Feature Request Description"
      description: "Provide a detailed description of the feature you are requesting."
      placeholder: "I want to be able to..."
    validations:
      required: true

  - type: textarea
    attributes:
      label: "Code Example or Use-Case"
      description: |-
        Provide some code or describe a possible use-case for this feature.
        
        The provided text will be rendered as Java code, so you don't have to provide a Code block for it.
      placeholder: "public void newAwesomeMethod(){}"
      render: java